project = "<Enter your project name>"
db_username = "<Enter your DB username>"
db_password = "<Enter your DB password>"
db_name = "<Enter your DB name>"
role_arn = "arn:aws:iam::<account-ID>:role/<Enter the role name>"
public_key = "<Enter your public ssh-rsa key>"
